import { slugify } from "@/lib/utils/slug";
import { DEFAULT_CURRENCY, DEFAULT_RETURN_POLICY, DEFAULT_SHIPPING_ESTIMATE, resolvePurchaseMode } from "./config";
import type {
  Authentication,
  Money,
  Product,
  ProductFilters,
  ProductImage,
  ProductSort,
} from "./types";

function money(amount: number): Money {
  return { amount, currency: DEFAULT_CURRENCY };
}

function authentication(certified: boolean): Authentication {
  return certified
    ? {
        checkedInStore: true,
        provider: "Entrupy",
        certificateAvailable: true,
        invoiceAvailable: true,
      }
    : {
        checkedInStore: true,
        certificateAvailable: false,
        invoiceAvailable: true,
      };
}

function images(brand: string, title: string, count = 3, realSrc?: string): ProductImage[] {
  const alt = `${brand} ${title}`;
  if (realSrc) {
    return [{ url: realSrc, alt, width: 378, height: 473 }];
  }
  return Array.from({ length: count }, (_, i) => ({
    url: "placeholder",
    alt: i === 0 ? alt : `${alt} — detail ${i + 1}`,
    width: 1200,
    height: 1500,
  }));
}

type SeedProduct = Omit<
  Product,
  | "price"
  | "purchaseMode"
  | "images"
  | "thumbnail"
  | "authentication"
  | "shipping"
  | "returnPolicy"
  | "quantity"
> & {
  priceAmount: number;
  purchaseModeOverride?: Product["purchaseMode"];
  certified?: boolean;
  imageCount?: number;
  /** Real photo path (e.g. "/goyard-vendome-pouch.png"). Falls back to the gradient placeholder when omitted. */
  imageSrc?: string;
  quantity?: number;
};

function seed(p: SeedProduct): Product {
  return {
    ...p,
    price: money(p.priceAmount),
    purchaseMode: p.purchaseModeOverride ?? resolvePurchaseMode(p.priceAmount),
    images: images(p.brand, p.title, p.imageCount, p.imageSrc),
    thumbnail: images(p.brand, p.title, 1, p.imageSrc)[0],
    authentication: authentication(p.certified ?? false),
    shipping: DEFAULT_SHIPPING_ESTIMATE,
    returnPolicy: DEFAULT_RETURN_POLICY,
    quantity: p.quantity ?? (p.availability === "sold" ? 0 : 1),
  };
}

export const PRODUCTS: Product[] = [
  seed({
    id: "prod-chanel-classic-flap-medium",
    handle: "chanel-classic-flap-medium-black",
    title: "Classic Flap Medium",
    brand: "Chanel",
    designerHandle: "chanel",
    category: "bags",
    subcategory: "Shoulder Bags",
    description:
      "The quilted lambskin flap bag that has held its shape and its value since 1955. Medium size, gold-tone chain and turn-lock.",
    priceAmount: 385000,
    condition: "excellent",
    conditionNotes: "Light corner wear on the base. Interior clean. Original box and dust bag included.",
    colour: "Black",
    material: "Lambskin, gold-tone hardware",
    dimensions: "25 × 15.5 × 6.5 cm",
    year: 2019,
    gender: "women",
    availability: "in_stock",
    sku: "CHN-BAG-0001",
    tags: ["quilted", "chain-strap", "everyday"],
    collectionIds: ["col-icons-revisited", "col-investment-pieces", "col-bags-worth-collecting"],
    featured: true,
    newArrival: false,
    rarePiece: false,
    editorPick: true,
    certified: true,
    createdAt: "2026-05-12",
  }),
  seed({
    id: "prod-hermes-birkin-30-togo",
    handle: "hermes-birkin-30-togo-etoupe",
    title: "Birkin 30",
    brand: "Hermès",
    designerHandle: "hermes",
    category: "bags",
    subcategory: "Top Handle",
    description:
      "Togo leather in Étoupe with palladium hardware. The Birkin remains the most requested bag we source — this one arrived through a private collection.",
    priceAmount: 1450000,
    condition: "excellent",
    conditionNotes: "Unworn corners, no scratches on hardware. Comes with clochette, cadena and original receipt.",
    colour: "Étoupe",
    material: "Togo leather, palladium hardware",
    dimensions: "30 × 22 × 16 cm",
    year: 2022,
    gender: "women",
    availability: "enquire",
    sku: "HRM-BAG-0002",
    tags: ["rare", "waitlist-piece"],
    collectionIds: ["col-icons-revisited", "col-investment-pieces", "col-bags-worth-collecting"],
    featured: true,
    newArrival: false,
    rarePiece: true,
    editorPick: true,
    certified: true,
    createdAt: "2026-06-02",
  }),
  seed({
    id: "prod-lv-neverfull-mm",
    handle: "louis-vuitton-neverfull-mm-monogram",
    title: "Neverfull MM",
    brand: "Louis Vuitton",
    designerHandle: "louis-vuitton",
    category: "bags",
    subcategory: "Tote",
    description: "Monogram canvas tote with the removable pouch. A daily bag built to be used, not shelved.",
    priceAmount: 95000,
    condition: "very_good",
    conditionNotes: "Canvas corners show light patina consistent with regular use. Leather trim unmarked.",
    colour: "Monogram / Beige",
    material: "Coated canvas, cowhide trim",
    dimensions: "32 × 29 × 17 cm",
    year: 2021,
    gender: "women",
    availability: "in_stock",
    sku: "LV-BAG-0003",
    tags: ["tote", "everyday", "monogram"],
    collectionIds: ["col-new-arrivals", "col-icons-revisited", "col-bags-worth-collecting"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-08-14",
  }),
  seed({
    id: "prod-dior-lady-dior-medium",
    handle: "dior-lady-dior-medium-cannage",
    title: "Lady Dior Medium",
    brand: "Dior",
    designerHandle: "dior",
    category: "bags",
    subcategory: "Top Handle",
    description: "Cannage-quilted lambskin with the Dior charm. Structured, ladylike, dependable.",
    priceAmount: 310000,
    condition: "excellent",
    colour: "Black",
    material: "Lambskin, gold-tone hardware",
    dimensions: "24 × 20 × 11 cm",
    year: 2020,
    gender: "women",
    availability: "low_stock",
    sku: "DIOR-BAG-0004",
    tags: ["structured", "top-handle"],
    collectionIds: ["col-bags-worth-collecting"],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    certified: true,
    createdAt: "2026-03-22",
  }),
  seed({
    id: "prod-gucci-marmont-small",
    handle: "gucci-gg-marmont-small-shoulder-bag",
    title: "GG Marmont Small",
    brand: "Gucci",
    designerHandle: "gucci",
    category: "bags",
    subcategory: "Shoulder Bags",
    description: "Matelassé chevron leather with the antique-gold double G. A quieter entry point into the house.",
    priceAmount: 78000,
    condition: "good",
    conditionNotes: "Visible corner wear and light marks on the flap consistent with age.",
    colour: "Black",
    material: "Chevron leather",
    dimensions: "26 × 15 × 7 cm",
    year: 2018,
    gender: "women",
    availability: "in_stock",
    sku: "GUC-BAG-0005",
    tags: ["chain-strap"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-01-30",
  }),
  seed({
    id: "prod-bottega-cassette",
    handle: "bottega-veneta-cassette-intrecciato",
    title: "Cassette Bag",
    brand: "Bottega Veneta",
    designerHandle: "bottega-veneta",
    category: "bags",
    subcategory: "Shoulder Bags",
    description: "Padded intrecciato leather in a slim crossbody silhouette. No branding — the weave speaks.",
    priceAmount: 145000,
    condition: "excellent",
    colour: "Espresso",
    material: "Intrecciato lambskin",
    dimensions: "20 × 13.5 × 7.5 cm",
    year: 2023,
    gender: "women",
    availability: "in_stock",
    sku: "BV-BAG-0006",
    tags: ["crossbody", "woven"],
    collectionIds: ["col-new-arrivals", "col-bags-worth-collecting"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-08-05",
  }),
  seed({
    id: "prod-ysl-kate-bag",
    handle: "saint-laurent-kate-medium-tassel-bag",
    title: "Kate Medium Tassel Bag",
    brand: "Saint Laurent",
    designerHandle: "saint-laurent",
    category: "bags",
    subcategory: "Shoulder Bags",
    description: "Grain de poudre leather with the signature tassel. Sold to a collector in June — kept here for reference.",
    priceAmount: 62000,
    condition: "very_good",
    colour: "Black",
    material: "Grain de poudre leather",
    dimensions: "24 × 14.5 × 6 cm",
    year: 2019,
    gender: "women",
    availability: "sold",
    sku: "YSL-BAG-0007",
    tags: ["tassel", "chain-strap"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2025-11-18",
  }),
  seed({
    id: "prod-prada-re-edition-2005",
    handle: "prada-re-edition-2005-nylon",
    title: "Re-Edition 2005",
    brand: "Prada",
    designerHandle: "prada",
    category: "bags",
    subcategory: "Shoulder Bags",
    description: "Re-issued from the 2005 archive in re-nylon. Compact, technical, quietly recognisable.",
    priceAmount: 58000,
    condition: "excellent",
    colour: "Black",
    material: "Re-nylon, saffiano trim",
    dimensions: "22 × 15 × 5 cm",
    year: 2022,
    gender: "women",
    availability: "in_stock",
    sku: "PRD-BAG-0008",
    tags: ["nylon", "archive"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-02-08",
  }),
  seed({
    id: "prod-goyard-petit-mini-bucket-bag",
    handle: "goyard-petit-mini-bucket-bag-yellow",
    title: "Petit Mini Bucket Bag",
    brand: "Goyard",
    designerHandle: "goyard",
    category: "bags",
    subcategory: "Bucket Bags",
    description: "Hand-painted chevron canvas in a compact bucket silhouette, with the signature drawstring top.",
    priceAmount: 225000,
    condition: "excellent",
    colour: "Yellow",
    material: "Coated canvas, leather trim",
    dimensions: "12 × 15 × 12 cm",
    year: 2023,
    gender: "women",
    availability: "in_stock",
    sku: "GOY-BAG-0027",
    tags: ["bucket-bag", "chevron-canvas"],
    collectionIds: ["col-new-arrivals", "col-bags-worth-collecting"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    certified: true,
    imageSrc: "/GOYARD-PETIT-MINI-BUCKET-BAG-YELLOW.png",
    createdAt: "2026-08-25",
  }),
  seed({
    id: "prod-mcqueen-slash-pouch",
    handle: "alexander-mcqueen-slash-pouch-welsh-red",
    title: "The Slash Pouch, Welsh Red",
    brand: "Alexander McQueen",
    designerHandle: "alexander-mcqueen",
    category: "bags",
    subcategory: "Pouches",
    description: "Padded leather pouch with the sculpted slash seams that run through the house's leather goods.",
    priceAmount: 45000,
    condition: "excellent",
    colour: "Red",
    material: "Leather",
    dimensions: "30 × 21 × 3 cm",
    year: 2023,
    gender: "unisex",
    availability: "in_stock",
    sku: "AMQ-BAG-0028",
    tags: ["pouch", "leather"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    imageSrc: "/ALEXANDER-MCQUEEN-SLASH-POUCH-WELSH-RED.png",
    createdAt: "2026-08-24",
  }),
  seed({
    id: "prod-goyard-beluga-mini",
    handle: "goyard-beluga-mini-tan",
    title: "Beluga Mini",
    brand: "Goyard",
    designerHandle: "goyard",
    category: "bags",
    subcategory: "Top Handle",
    description: "A structured top-handle in chevron canvas with the cut-out handle Goyard introduced on the Beluga.",
    priceAmount: 295000,
    condition: "excellent",
    colour: "Tan",
    material: "Coated canvas, leather trim",
    dimensions: "18 × 13 × 10 cm",
    year: 2022,
    gender: "women",
    availability: "in_stock",
    sku: "GOY-BAG-0029",
    tags: ["top-handle", "chevron-canvas"],
    collectionIds: ["col-new-arrivals", "col-bags-worth-collecting"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    certified: true,
    imageSrc: "/GOYARD-BELUGA-MINI-TAN.png",
    createdAt: "2026-08-25",
  }),
  seed({
    id: "prod-polene-numero-dix-micro",
    handle: "polene-numero-dix-micro-handbag",
    title: "Numéro Dix Micro",
    brand: "Polène",
    designerHandle: "polene",
    category: "bags",
    subcategory: "Shoulder Bags",
    description: "The curved, hardware-free silhouette that made Numéro Dix recognisable, in the micro size.",
    priceAmount: 32000,
    condition: "unworn",
    colour: "Dark Brown",
    material: "Leather",
    dimensions: "17 × 12 × 5 cm",
    year: 2024,
    gender: "women",
    availability: "in_stock",
    sku: "POL-BAG-0030",
    tags: ["saddle", "minimalist"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    imageSrc: "/POLENE-NUMERO-DIX-MICRO-HANDBAG.png",
    createdAt: "2026-08-23",
  }),
  seed({
    id: "prod-mcqueen-slash-shoulder-bag",
    handle: "alexander-mcqueen-the-slash-leather-shoulder-bag",
    title: "The Slash Leather Shoulder Bag",
    brand: "Alexander McQueen",
    designerHandle: "alexander-mcqueen",
    category: "bags",
    subcategory: "Shoulder Bags",
    description: "Structured leather with the sculpted slash seams and the jewelled skull clasp.",
    priceAmount: 80000,
    condition: "excellent",
    colour: "Ivory",
    material: "Leather, jewelled hardware",
    dimensions: "26 × 18 × 8 cm",
    year: 2023,
    gender: "women",
    availability: "in_stock",
    sku: "AMQ-BAG-0031",
    tags: ["shoulder-bag", "statement-hardware"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    imageSrc: "/ALEXANDER-MCQUEEN-THE-SLASH-LEATHER-SHOULDR-BAG.png",
    createdAt: "2026-08-22",
  }),
  seed({
    id: "prod-valentino-vlogo-bucket-bag",
    handle: "valentino-vlogo-leather-bucket-bag-blue",
    title: "VLogo Leather Bucket Bag",
    brand: "Valentino",
    designerHandle: "valentino",
    category: "bags",
    subcategory: "Bucket Bags",
    description: "Smooth leather bucket bag with the VLogo cut into the front panel and a drawstring closure.",
    priceAmount: 75000,
    condition: "excellent",
    colour: "Blue",
    material: "Leather, gold-tone hardware",
    dimensions: "20 × 22 × 12 cm",
    year: 2022,
    gender: "women",
    availability: "in_stock",
    sku: "VAL-BAG-0032",
    tags: ["bucket-bag", "vlogo"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    imageSrc: "/VALENTINO-VLOGO-LEATHER-BUCKET-BAG-BLUE.png",
    createdAt: "2026-08-21",
  }),
  seed({
    id: "prod-goyard-vendome-pouch",
    handle: "goyard-vendome-pouch",
    title: "Vendôme Pouch",
    brand: "Goyard",
    designerHandle: "goyard",
    category: "bags",
    subcategory: "Pouches",
    description: "Chevron canvas pouch sized for the everyday carry, with a leather-trimmed zip closure.",
    priceAmount: 95000,
    condition: "excellent",
    colour: "Blue",
    material: "Coated canvas, leather trim",
    dimensions: "24 × 18 × 8 cm",
    year: 2023,
    gender: "unisex",
    availability: "in_stock",
    sku: "GOY-BAG-0033",
    tags: ["pouch", "chevron-canvas"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    certified: true,
    imageSrc: "/GOYARD-VENDOME-POUCH.png",
    createdAt: "2026-08-20",
  }),

  // Watches
  seed({
    id: "prod-rolex-datejust-36",
    handle: "rolex-datejust-36-jubilee",
    title: "Datejust 36",
    brand: "Rolex",
    designerHandle: "rolex",
    category: "watches",
    description: "Steel and white gold on the Jubilee bracelet, fluted bezel. Serviced ahead of listing.",
    priceAmount: 720000,
    condition: "excellent",
    conditionNotes: "Recently serviced by an authorised centre. Full service record available on request.",
    colour: "Silver dial",
    material: "Steel, white gold bezel",
    year: 2017,
    gender: "unisex",
    availability: "enquire",
    sku: "RLX-WCH-0009",
    tags: ["steel", "jubilee-bracelet"],
    collectionIds: ["col-investment-pieces"],
    featured: true,
    newArrival: false,
    rarePiece: true,
    editorPick: false,
    certified: true,
    createdAt: "2026-04-19",
  }),
  seed({
    id: "prod-cartier-tank-francaise",
    handle: "cartier-tank-francaise-medium",
    title: "Tank Française Medium",
    brand: "Cartier",
    designerHandle: "cartier",
    category: "watches",
    description: "The Tank in steel, on its own link bracelet. Currently held for a returning client — enquiries welcome.",
    priceAmount: 410000,
    condition: "excellent",
    colour: "Silver dial",
    material: "Steel",
    year: 2020,
    gender: "women",
    availability: "reserved",
    sku: "CTR-WCH-0010",
    tags: ["steel", "bracelet"],
    collectionIds: ["col-icons-revisited"],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    certified: true,
    createdAt: "2026-07-01",
  }),
  seed({
    id: "prod-rolex-submariner-date",
    handle: "rolex-submariner-date-black",
    title: "Submariner Date",
    brand: "Rolex",
    designerHandle: "rolex",
    category: "watches",
    description: "Black dial, ceramic bezel, Oystersteel bracelet. One of the pieces clients ask us to source before it ever reaches the floor.",
    priceAmount: 980000,
    condition: "very_good",
    conditionNotes: "Light bracelet stretch, consistent with age. Box only, papers not available.",
    colour: "Black dial",
    material: "Oystersteel, ceramic bezel",
    year: 2016,
    gender: "men",
    availability: "enquire",
    sku: "RLX-WCH-0011",
    tags: ["dive-watch", "ceramic-bezel"],
    collectionIds: ["col-icons-revisited", "col-investment-pieces"],
    featured: false,
    newArrival: false,
    rarePiece: true,
    editorPick: true,
    certified: true,
    createdAt: "2026-05-28",
  }),
  seed({
    id: "prod-cartier-santos",
    handle: "cartier-santos-de-cartier-large",
    title: "Santos de Cartier Large",
    brand: "Cartier",
    designerHandle: "cartier",
    category: "watches",
    description: "The reissued Santos with the QuickSwitch bracelet system. Steel case, exposed screws.",
    priceAmount: 520000,
    purchaseModeOverride: "enquiry",
    condition: "excellent",
    colour: "Silver dial",
    material: "Steel",
    year: 2021,
    gender: "men",
    availability: "in_stock",
    sku: "CTR-WCH-0012",
    tags: ["steel", "interchangeable-strap"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    certified: true,
    createdAt: "2026-06-25",
  }),

  // Jewellery
  seed({
    id: "prod-cartier-love-bracelet",
    handle: "cartier-love-bracelet-yellow-gold",
    title: "Love Bracelet",
    brand: "Cartier",
    designerHandle: "cartier",
    category: "jewellery",
    description: "Yellow gold, size 17. Sold with the original screwdriver.",
    priceAmount: 285000,
    condition: "excellent",
    colour: "Yellow Gold",
    material: "18k yellow gold",
    dimensions: "Size 17",
    year: 2021,
    gender: "women",
    availability: "in_stock",
    sku: "CTR-JWL-0013",
    tags: ["gold", "stackable"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    certified: true,
    createdAt: "2026-08-01",
  }),
  seed({
    id: "prod-cartier-juste-un-clou",
    handle: "cartier-juste-un-clou-bracelet",
    title: "Juste un Clou Bracelet",
    brand: "Cartier",
    designerHandle: "cartier",
    category: "jewellery",
    description: "The nail, reimagined as jewellery since 1971. Small model in yellow gold.",
    priceAmount: 195000,
    condition: "very_good",
    colour: "Yellow Gold",
    material: "18k yellow gold",
    year: 2019,
    gender: "unisex",
    availability: "in_stock",
    sku: "CTR-JWL-0014",
    tags: ["gold", "unisex"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    certified: true,
    createdAt: "2026-02-19",
  }),
  seed({
    id: "prod-chanel-pearl-necklace",
    handle: "chanel-fine-pearl-necklace",
    title: "Fine Pearl Necklace",
    brand: "Chanel",
    designerHandle: "chanel",
    category: "jewellery",
    description: "Vintage-line pearl necklace with the CC clasp. One of a small run.",
    priceAmount: 165000,
    condition: "good",
    conditionNotes: "Clasp shows light surface wear; pearls in original condition.",
    colour: "Cream",
    material: "Faux pearl, gold-tone metal",
    year: 2015,
    gender: "women",
    availability: "low_stock",
    sku: "CHN-JWL-0015",
    tags: ["vintage", "pearl"],
    collectionIds: ["col-evening-edit"],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-01-11",
  }),
  seed({
    id: "prod-cartier-panthere-ring",
    handle: "cartier-panthere-ring-diamond",
    title: "Panthère Ring, Diamond Pavé",
    brand: "Cartier",
    designerHandle: "cartier",
    category: "jewellery",
    description: "White gold Panthère head, pavé diamonds, emerald eyes and onyx spots. Reserved pending a viewing.",
    priceAmount: 610000,
    condition: "excellent",
    colour: "White Gold",
    material: "18k white gold, diamonds, emerald, onyx",
    year: 2020,
    gender: "women",
    availability: "reserved",
    sku: "CTR-JWL-0016",
    tags: ["rare", "diamond"],
    collectionIds: ["col-evening-edit", "col-investment-pieces"],
    featured: false,
    newArrival: false,
    rarePiece: true,
    editorPick: false,
    certified: true,
    createdAt: "2026-07-15",
  }),

  // Shoes
  seed({
    id: "prod-chanel-ballet-flats",
    handle: "chanel-quilted-ballet-flats",
    title: "Quilted Ballet Flats",
    brand: "Chanel",
    designerHandle: "chanel",
    category: "shoes",
    description: "The two-tone cap-toe flat, quilted leather, grosgrain trim.",
    priceAmount: 42000,
    condition: "very_good",
    colour: "Black / Beige",
    material: "Lambskin",
    size: "EU 38",
    year: 2020,
    gender: "women",
    availability: "in_stock",
    sku: "CHN-SHO-0017",
    tags: ["flats", "two-tone"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-03-02",
  }),
  seed({
    id: "prod-gucci-horsebit-loafers",
    handle: "gucci-horsebit-loafers-leather",
    title: "Horsebit Loafers",
    brand: "Gucci",
    designerHandle: "gucci",
    category: "shoes",
    description: "The original loafer silhouette from 1953, in polished calfskin with the horsebit detail.",
    priceAmount: 48000,
    condition: "excellent",
    colour: "Black",
    material: "Calfskin",
    size: "EU 43",
    year: 2022,
    gender: "men",
    availability: "in_stock",
    sku: "GUC-SHO-0018",
    tags: ["loafers", "leather-sole"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-08-10",
  }),
  seed({
    id: "prod-lv-archlight-sneakers",
    handle: "louis-vuitton-archlight-sneakers",
    title: "Archlight Sneakers",
    brand: "Louis Vuitton",
    designerHandle: "louis-vuitton",
    category: "shoes",
    description: "Chunky-sole sneaker with the layered LV logo. Sold — kept here as a reference piece.",
    priceAmount: 39000,
    condition: "good",
    colour: "White / Silver",
    material: "Mesh, leather, rubber",
    size: "EU 37",
    year: 2019,
    gender: "women",
    availability: "sold",
    sku: "LV-SHO-0019",
    tags: ["sneakers"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2025-12-20",
  }),
  seed({
    id: "prod-ysl-opyum-pumps",
    handle: "saint-laurent-opyum-pumps",
    title: "Opyum Pumps",
    brand: "Saint Laurent",
    designerHandle: "saint-laurent",
    category: "shoes",
    description: "The opium-poppy heel in patent leather. Evening-ready, unmistakably YSL.",
    priceAmount: 51000,
    condition: "excellent",
    colour: "Black",
    material: "Patent leather",
    size: "EU 38.5",
    year: 2021,
    gender: "women",
    availability: "low_stock",
    sku: "YSL-SHO-0020",
    tags: ["heels", "evening"],
    collectionIds: ["col-evening-edit"],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-04-02",
  }),

  // Accessories
  seed({
    id: "prod-hermes-silk-carre",
    handle: "hermes-silk-carre-scarf",
    title: "Silk Carré Scarf, 90cm",
    brand: "Hermès",
    designerHandle: "hermes",
    category: "accessories",
    description: "Hand-rolled hems, screen-printed silk twill. Never worn, with original box.",
    priceAmount: 28000,
    condition: "unworn",
    colour: "Multicolour",
    material: "Silk twill",
    dimensions: "90 × 90 cm",
    year: 2024,
    gender: "unisex",
    availability: "in_stock",
    sku: "HRM-ACC-0021",
    tags: ["silk", "gift"],
    collectionIds: ["col-new-arrivals"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: true,
    createdAt: "2026-08-18",
  }),
  seed({
    id: "prod-gucci-gg-belt",
    handle: "gucci-gg-marmont-belt",
    title: "GG Marmont Belt",
    brand: "Gucci",
    designerHandle: "gucci",
    category: "accessories",
    description: "Leather belt with the antique-gold double-G buckle.",
    priceAmount: 22000,
    condition: "very_good",
    colour: "Black",
    material: "Leather",
    size: "90 cm",
    year: 2020,
    gender: "unisex",
    availability: "in_stock",
    sku: "GUC-ACC-0022",
    tags: ["leather", "buckle"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-01-05",
  }),
  seed({
    id: "prod-lv-damier-wallet",
    handle: "louis-vuitton-damier-long-wallet",
    title: "Damier Long Wallet",
    brand: "Louis Vuitton",
    designerHandle: "louis-vuitton",
    category: "accessories",
    description: "Damier Ebène canvas, zip coin compartment, eight card slots.",
    priceAmount: 34000,
    condition: "good",
    colour: "Damier Ebène",
    material: "Coated canvas",
    year: 2018,
    gender: "unisex",
    availability: "in_stock",
    sku: "LV-ACC-0023",
    tags: ["wallet", "canvas"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2025-10-29",
  }),

  // Clothing
  seed({
    id: "prod-dior-bar-jacket",
    handle: "dior-bar-jacket-wool",
    title: "Bar Jacket, Wool Crepe",
    brand: "Dior",
    designerHandle: "dior",
    category: "clothing",
    description: "The silhouette that defined the New Look in 1947 — nipped waist, rounded hip, structured shoulder.",
    priceAmount: 165000,
    condition: "excellent",
    colour: "Ivory",
    material: "Wool crepe",
    size: "FR 38",
    year: 2019,
    gender: "women",
    availability: "in_stock",
    sku: "DIOR-CLO-0024",
    tags: ["tailoring", "archive"],
    collectionIds: ["col-evening-edit"],
    featured: false,
    newArrival: false,
    rarePiece: true,
    editorPick: true,
    certified: false,
    createdAt: "2026-05-30",
  }),
  seed({
    id: "prod-ysl-le-smoking",
    handle: "saint-laurent-le-smoking-blazer",
    title: "Le Smoking Blazer",
    brand: "Saint Laurent",
    designerHandle: "saint-laurent",
    category: "clothing",
    description: "The tuxedo jacket that moved trousers onto every woman's shoulders. Satin lapel, single button.",
    priceAmount: 88000,
    condition: "very_good",
    colour: "Black",
    material: "Wool, satin lapel",
    size: "FR 36",
    year: 2020,
    gender: "women",
    availability: "in_stock",
    sku: "YSL-CLO-0025",
    tags: ["tailoring", "evening"],
    collectionIds: ["col-new-arrivals", "col-evening-edit"],
    featured: false,
    newArrival: true,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-08-12",
  }),
  seed({
    id: "prod-gucci-bomber",
    handle: "gucci-bomber-jacket-embroidered",
    title: "Embroidered Bomber Jacket",
    brand: "Gucci",
    designerHandle: "gucci",
    category: "clothing",
    description: "Silk bomber with tiger embroidery on the back panel. Ribbed collar and cuffs.",
    priceAmount: 72000,
    condition: "good",
    colour: "Navy",
    material: "Silk",
    size: "IT 50",
    year: 2017,
    gender: "men",
    availability: "low_stock",
    sku: "GUC-CLO-0026",
    tags: ["embroidered", "statement"],
    collectionIds: [],
    featured: false,
    newArrival: false,
    rarePiece: false,
    editorPick: false,
    createdAt: "2026-02-25",
  }),
];

export function getAllProducts(): Product[] {
  return PRODUCTS;
}

export function getProductByHandle(handle: string): Product | undefined {
  return PRODUCTS.find((p) => p.handle === handle);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getFeaturedProducts(limit = 4): Product[] {
  return PRODUCTS.filter((p) => p.featured).slice(0, limit);
}

export function getNewArrivals(limit = 8): Product[] {
  return [...PRODUCTS]
    .filter((p) => p.newArrival)
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1))
    .slice(0, limit);
}

export function getEditorPicks(limit = 6): Product[] {
  return PRODUCTS.filter((p) => p.editorPick).slice(0, limit);
}

export function getProductsByDesigner(designerHandle: string): Product[] {
  return PRODUCTS.filter((p) => p.designerHandle === designerHandle);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductsByCollection(collectionId: string): Product[] {
  return PRODUCTS.filter((p) => p.collectionIds.includes(collectionId));
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      (p.category === product.category || p.designerHandle === product.designerHandle)
  ).slice(0, limit);
}

export function searchProducts(query: string, limit = 12): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return PRODUCTS.filter((p) =>
    [p.title, p.brand, p.category, p.subcategory ?? "", p.sku]
      .join(" ")
      .toLowerCase()
      .includes(q)
  ).slice(0, limit);
}

export function filterProducts(filters: ProductFilters, sort: ProductSort = "newest"): Product[] {
  let results = [...PRODUCTS];

  if (filters.category) results = results.filter((p) => p.category === filters.category);
  if (filters.designerHandle) results = results.filter((p) => p.designerHandle === filters.designerHandle);
  if (filters.designerHandles?.length) {
    results = results.filter((p) => filters.designerHandles!.includes(p.designerHandle));
  }
  if (filters.subcategory?.length) {
    results = results.filter((p) => p.subcategory && filters.subcategory!.includes(slugify(p.subcategory)));
  }
  if (filters.collectionHandle) {
    results = results.filter((p) => p.collectionIds.includes(filters.collectionHandle!));
  }
  if (filters.gender) results = results.filter((p) => p.gender === filters.gender || p.gender === "unisex");
  if (filters.condition?.length) results = results.filter((p) => filters.condition!.includes(p.condition));
  if (filters.availability?.length) {
    results = results.filter((p) => filters.availability!.includes(p.availability));
  }
  if (filters.colour?.length) {
    results = results.filter((p) => p.colour && filters.colour!.includes(p.colour));
  }
  if (filters.size?.length) {
    results = results.filter((p) => p.size && filters.size!.includes(p.size));
  }
  if (typeof filters.priceMin === "number") {
    results = results.filter((p) => p.price.amount >= filters.priceMin!);
  }
  if (typeof filters.priceMax === "number") {
    results = results.filter((p) => p.price.amount <= filters.priceMax!);
  }
  if (filters.query) {
    const q = filters.query.trim().toLowerCase();
    results = results.filter((p) => [p.title, p.brand].join(" ").toLowerCase().includes(q));
  }

  switch (sort) {
    case "price_asc":
      results.sort((a, b) => a.price.amount - b.price.amount);
      break;
    case "price_desc":
      results.sort((a, b) => b.price.amount - a.price.amount);
      break;
    case "newest":
      results.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
      break;
    default:
      break;
  }

  return results;
}
